FROM ruby:3.4.1-alpine

RUN apk -U add --no-cache \
  build-base \
  git \
  postgresql-dev \
  postgresql-client \
  libxml2-dev \
  libxslt-dev \
  nodejs-current \
  tzdata \
  less \
  && rm -rf /var/cache/apk/*

ENV APP_PATH /var/app
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true
ENV RAILS_PORT 3001

ENV BUNDLE_PATH /bundle/vendor
ENV BUNDLE_VERSION 2.6.2

RUN mkdir -p $APP_PATH

COPY ./dev-entrypoint.sh /usr/local/bin/dev-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-entrypoint.sh

RUN gem install bundler --version "$BUNDLE_VERSION" \
  && rm -rf $GEM_HOME/cache/*

WORKDIR $APP_PATH

EXPOSE $RAILS_PORT

ENTRYPOINT ["bundle", "exec"]
